all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ssh_key_path: ~/.ssh/poove.poos.home

local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: 127.0.0.1
      ansible_user: root

proxmox:
  hosts:
    # poove1.poos.home:
    #   ansible_host: 192.168.1.81
    #   ansible_user: root
    #   ansible_ssh_private_key_file: "{{ ssh_key_path }}"
    poove2.poos.home:
      ansible_host: 192.168.1.86
      ansible_user: root
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"
