apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: prometheus-vs
  namespace: nginx
spec:
  host: prometheus.poos.home
  routes:
    - path: /
      route: monitoring/prometheus-vsr

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: prometheus-vsr
  namespace: monitoring
spec:
  host: prometheus.poos.home
  upstreams:
    - name: server
      service: poometheus-prometheus-server
      port: 80
  subroutes:
    - path: /
      action:
        pass: server
