---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vaultwarden-pv
  namespace: vaultwarden
  labels:
    type: local
spec:
  storageClassName: vaultwarden-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/srv/shared/vaultwarden"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vaultwarden-sc
  namespace: vaultwarden
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer