---
apiVersion: v1
kind: Service
metadata:
  name: "pihole-web-svc"
  namespace: "pihole"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
      name: "http"
  selector:
    app: "pihole"

---
apiVersion: v1
kind: Service
metadata:
  name: "pihole-dns-svc"
  namespace: "pihole"
spec:
  ports:
    - port: 53
      targetPort: 53
      protocol: "UDP"
      name: "dnsu"
    - port: 53
      targetPort: 53
      protocol: "TCP"
      name: "dnst"
  selector:
    app: "pihole"

---
apiVersion: v1
kind: Service
metadata:
  name: "pihole-dhcp-svc"
  namespace: "pihole"
spec:
  ports:
    - port: 67
      targetPort: 67
      protocol: "UDP"
      name: "dhcpu"
  selector:
    app: "pihole"

---
apiVersion: v1
kind: Service
metadata:
  name: "pihole-dns-svc-ext"
  namespace: "pihole"
spec:
  ports:
    - port: 53
      targetPort: 53
      protocol: "UDP"
      name: "dnsu"
    - port: 53
      targetPort: 53
      protocol: "TCP"
      name: "dnst"
  type: LoadBalancer
  loadBalancerIP: 192.168.1.253
  selector:
    app: "pihole"

---
apiVersion: v1
kind: Service
metadata:
  name: "pihole-exporter"
  namespace: "pihole"
spec:
  type: ClusterIP
  ports:
    - port: 9617
      targetPort: 9617
      protocol: TCP
      name: exporter-port
  selector:
    app.kubernetes.io/name: pihole-exporter
    app.kubernetes.io/instance: pihole-exporter