controller:
  enableSnippets: "true"
  service:
    loadBalancerIP: "192.168.1.254"
    customPorts:
      - name: tcp-dns
        port: 53
        protocol: TCP
      - name: udp-dns
        port: 53
        protocol: UDP
      - name: dhcp
        port: 67
        protocol: UDP
  rbac:
    create: "true"
  globalConfiguration:
    create: "true"
    spec:
      listeners:
        - name: pihole-tcp
          port: 53
          protocol: TCP
        - name: pihole-udp
          port: 53
          protocol: UDP
        - name: pihole-dhcp
          port: 67
          protocol: UDP
