apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        kubernetes.io/metadata.name: metallb
      name: metallb
    spec:
      finalizers:
      - kubernetes
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        kubernetes.io/metadata.name: nginx
      name: nginx
    spec:
      finalizers:
      - kubernetes
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        kubernetes.io/metadata.name: portainer
      name: portainer
    spec:
      finalizers:
      - kubernetes
