apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2021.10
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          env:
            - name: TZ
              value: "America/New_York"
            - name: WEBPASSWORD
              value: secret
            - name: WEBPASSWORD
              value: secret
            - name: DNS1
              value: 1.1.1.1
            - name: DNS2
              value: no
            - name: VIRTUAL_HOST
              value: pi.hole
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 1


  #     volumeMounts:
  #       - name: etc
  #         mountPath: /etc/pihole
  #       - name: dnsmasq
  #         mountPath: /etc/dnsmasq.d
  # volumes:
  #   - name: etc
  #     hostPath:
  #       path: /data/pihole/etc
  #       type: Directory
  #   - name: dnsmasq
  #     hostPath:
  #       path: /data/pihole/dnsmasq.d
  #       type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-svc
  namespace: pihole
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: pihole
