apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: pihole-tcp
  namespace: pihole
spec:
  listener:
    name: pihole-tcp 
    protocol: TCP
  upstreams:
    - name: dns-app
      service: pihole-dns-svc
      port: 53
  action:
    pass: dns-app

---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: pihole-udp
  namespace: pihole
spec:
  listener:
    name: pihole-udp 
    protocol: UDP 
  upstreams:
    - name: dns-app
      service: pihole-dns-svc
      port: 53
  upstreamParameters:
    udpRequests: 1
    udpResponses: 1
  action:
    pass: dns-app

---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: pihole-dhcp
  namespace: pihole
spec:
  listener:
    name: pihole-dhcp 
    protocol: UDP 
  upstreams:
    - name: dhcp-app
      service: pihole-dhcp-svc
      port: 67
  upstreamParameters:
    udpRequests: 1
    udpResponses: 1
  action:
    pass: dhcp-app
