apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: prometheus
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534      
      containers:
        - name: prometheus
          image: prom/prometheus:v2.37.0
          args:
            - "--storage.tsdb.retention.time=7d"
            - "--storage.tsdb.retention.size=4GB"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.external-url=http://10.211.55.240/prometheus"
            - "--web.route-prefix=/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 250M
            limits:
              cpu: "1"
              memory: 500M
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
              subPath: prometheus.yml
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-local-pvc
