kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: prometheus-local-storage
  namespace: prometheus
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-local-pv
  namespace: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-local-storage
  local:
    path: /mnt/srv/shared/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/instance-type
          operator: In
          values:
          - k3s        
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-local-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-local-storage
  resources:
    requests:
      storage: 5Gi
