---
apiVersion: v1
kind: Service
metadata:
  name: "unbound-dns-svc"
  namespace: "unbound"
spec:
  ports:
    - port: 5353
      targetPort: 5353
      protocol: "UDP"
      name: "dnsu"
    - port: 5353
      targetPort: 5353
      protocol: "TCP"
      name: "dnst"
  selector:
    app: "unbound"
