---
apiVersion: v1
kind: Service
metadata:
  name: "unbound-dns-svc"
  namespace: "unbound"
spec:
  ports:
    - port: 5353
      targetPort: 53
      protocol: "UDP"
      name: "dnsu"
    - port: 5353
      targetPort: 53
      protocol: "TCP"
      name: "dnst"
  clusterIP: 10.43.34.01
  selector:
    app: "unbound"
