apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "unbound"
  namespace: "unbound"
  labels:
    app.kubernetes.io/name: unbound
    app: unbound
spec:
  serviceName: unbound
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
      app: unbound
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unbound
        app: unbound
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - unbound
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: "unbound"
          image: "mvance/unbound:1.16.1"
          ports:
            - containerPort: 53
              protocol: "UDP"
            - containerPort: 53
              protocol: "TCP"
          env:
            - name:   "TZ"
              value:  "America/New_York"
          resources:
            requests:
              memory: "16Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "500m"
          volumeMounts:
            - name: "unbound-conf"
              mountPath: "/opt/unbound/etc/unbound/unbound.conf"
              readOnly: true
              subPath: unbound.conf
            - name: "unbound-extra-conf"
              mountPath: "/etc/unbound"
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - "drill"
                - "health.check.unbound"
                - "@127.0.0.1"
            initialDelaySeconds: 30
            timeoutSeconds: 2
      volumes:
        - name: "unbound-conf"
          configMap:
            name: unbounb-cfg
        - name: "unbound-extra-conf"
          configMap:
            name: unbounb-extra-cfg
